### ISSUE TITLE
Dont launch

### ISSUE THREAD

**Issue by BGiPV** [hypercyclist/snowrunner_save_editor#4]
Hello, version 1.04 does not start. Version 1.03 has this bug. What's happened. If you do not unpack and run from Winrar, they both turn on but do not open the .dat file.

![image](https://github.com/user-attachments/assets/28df480f-d6ed-4d6f-bb49-2a59498e921a)

**Comment by hypercyclist** [comment]
Hello. I know about this problem. Errors have one nature.
The solution is to place the program with the rest of the files in the root of the disk, so that the path is something like this:
С:\snowrunner_save_editor\snowrunner_save_editor.exe
D:\snowrunner_save_editor\snowrunner_save_editor.exe
This should help.

Why does this happen - too long paths in the program folder structure. This is somehow related to the fact that the program is trying to read a file, and the path to it is longer than 256 characters and Windows cannot read it.

**Comment by BGiPV** [comment]
Thanks, this helped
